# Working with Numpy in Python

In [2]:
#importing numpy
import numpy as np

## Simple Numpy Operations

In [3]:
list1 = [12, 23, 34, 45, 56, 67, 78, 89, 90]
np_array = np.array(list1)
print(np_array)

[12 23 34 45 56 67 78 89 90]


In [4]:
print(type(np_array))

<class 'numpy.ndarray'>


In [5]:
print(np_array.size)

9


In [6]:
print(np_array.ndim)

1


In [7]:
print(np_array.shape)

(9,)


In [8]:
np_array[0] = 15
np_array[1] = 25
np_array[2] = 35

In [9]:
print(np_array)

[15 25 35 45 56 67 78 89 90]


## Slicing of Arrays

In [10]:
#2nd to 6th element
sliced_array = np_array[1:6]
print(sliced_array)

[25 35 45 56 67]


In [11]:
#negative indexing
print(np_array[:-1])

[15 25 35 45 56 67 78 89]


## Vector Operations

In [12]:
#addition of elements
a = np.array([6, 1, 7, -3])
b = np.array([2, 5, -9, 5])
c = a + b
print(c)

[ 8  6 -2  2]


In [19]:
f = a + 7
print(f)

[13  8 14  4]


In [20]:
#multiplication with objects
d = np.array([3, 13, 71, 46])
e = d * 0.7
print(e)

[ 2.1  9.1 49.7 32.2]


In [21]:
#dot product
print(np.dot(a,  b))

-61


## Universal Numpy Functions

In [27]:
#finding mean of array
arr1 = np.array([23, 45, 55, 11, 77])
print(arr1.mean())

42.2


In [33]:
#finding max. value
print(arr1.max())

77


In [34]:
#finding std. deviation
print(arr1.std())

23.344378338263798


In [26]:
print(arr1.mean())

42.2


# 2-Dimensional Arrays and their Operations in Numpy

In [36]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
print(a)

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]


In [38]:
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [39]:
print(A.ndim)

2


In [40]:
print(A.size)

9


In [41]:
print(A.shape)

(3, 3)


In [42]:
#Accessing Elements
A[1,1]

22

In [43]:
A[0,2]

13

In [44]:
A[2,2]

33

In [47]:
# Access the element on the second row and second and third columns

print(A[1][1:3])

[22 23]


In [48]:
X = np.array([[1, 2, 3], [3, 5, 7]])
print(X)

[[1 2 3]
 [3 5 7]]


In [49]:
Y = np.array([[9, 2, 0], [2, 4, 6]])
print(Y)

[[9 2 0]
 [2 4 6]]


In [50]:
Z = X + Y
print(Z)

[[10  4  3]
 [ 5  9 13]]


Scalar Multilpication is same as 1-d array

In [53]:
#dot product
P = np.array([[0, 1, 1], [1, 0, 1]])
print(P)

[[0 1 1]
 [1 0 1]]


In [54]:
Q = np.array([[1, 1], [1, 1], [-1, 1]])
print(Q)

[[ 1  1]
 [ 1  1]
 [-1  1]]


In [55]:
R = np.dot(P, Q)
print(R)

[[0 2]
 [0 2]]


In [57]:
#transpose of matrix e.g: P
print(P.T)

[[0 1]
 [1 0]
 [1 1]]
